name: Deploy Zola Site

on:
  push:
    branches:
      - main  # Runs on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Zola
        run: |
          wget https://github.com/getzola/zola/releases/download/v0.20.0/zola-v0.20.0-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf zola-v0.20.0-x86_64-unknown-linux-gnu.tar.gz
          sudo mv zola /usr/local/bin/

      - name: Build Zola Site
        run: zola build

      - name: Upload Built Site to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          source: "public/*"
          target: "~/docker/ln-history-documentation/public"
          key_path: "/home/runner/.ssh/id_rsa"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/docker/ln-history-documentation
            docker-compose pull
            docker-compose down
            docker-compose up -d