name: Deploy Zola Site

on:
  push:
    branches:
      - main  # Runs on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Zola
        run: |
          wget https://github.com/getzola/zola/releases/download/v0.20.0/zola-v0.20.0-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf zola-x86_64-unknown-linux-gnu.tar.gz
          sudo mv zola /usr/local/bin/

      - name: Build Zola Site
        run: zola build

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy via SCP
        run: |
          scp -r public/* ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/var/www/ln-history